# Generated by Django 3.1 on 2020-08-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200826_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Id', models.CharField(max_length=200)),
                ('Turn', models.IntegerField()),
                ('Card_Id', models.IntegerField()),
                ('Player_Id', models.IntegerField()),
                ('Player_Vote', models.IntegerField()),
                ('Player_Score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
    ]
