# Generated by Django 3.1 on 2020-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_game_history_game_setup_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_setup',
            name='Current_Turn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
